/*
 *  Constants
 */
export const ADD_CLUSTER_GRAPH_DATA = "ADD_CLUSTER_GRAPH_DATA";
export const UPDATE_SELECTED_CLUSTERS = "UPDATE_SELECTED_CLUSTERS";
export const UPDATE_SELECTED_POINTS = "UPDATE_SELECTED_POINTS";